### ISSUE TITLE
1.3.5 — Moving an item within navigation

### ISSUE THREAD

**Issue by DialogusOne** [typemill/typemill#121] opened 2020-04-26 07:34 UTC
Working fine. Finis.

**Comment by trendschau** [comment] 2020-04-27 05:56
Thank you, I will have a look into ...

**Comment by trendschau** [comment] 2020-06-15 06:38
I could not reproduce an error anymore (and hard to reproduce without description). I hope the issue is fixed with other fixes I made with the navigation in version 1.3.7 published today.

**Closed by trendschau** 2020-06-15 06:38 UTC
Labels: bug
