### ISSUE TITLE
editor issue in admin panel

### ISSUE THREAD

**Issue by rantwolf** [typemill/typemill#241] opened 2020-12-11 20:34 UTC
hi. i'm using typemill for a small internal wiki.
i realized that there is an issue with the editor in the admin panel.
i wrote an article and saved it. 

![frontend-1](https://user-images.githubusercontent.com/39314130/101951024-93a52780-3bf6-11eb-9c2c-33bc9771d5a4.png)

after a few changes in this article i can't see the editor in admin panel referred to this article.

![backend-1](https://user-images.githubusercontent.com/39314130/101951361-2ba31100-3bf7-11eb-964b-f57edc3bf585.png)

but the tab with the meta-data correctly available.

![backend-2](https://user-images.githubusercontent.com/39314130/101951438-4a090c80-3bf7-11eb-89f3-8532d0f114b0.png)

if i'm opening the developer tools from chromium i get some errors:
`vue.min.js?20201130:6 ReferenceError: ct is not defined
    at wn.eval (eval at Ya (vue.min.js?20201130:6), <anonymous>:3:471)
    at wn.e._render (vue.min.js?20201130:6)
    at wn.r (vue.min.js?20201130:6)
    at fn.get (vue.min.js?20201130:6)
    at new fn (vue.min.js?20201130:6)
    at vue.min.js?20201130:6
    at wn.$mount (vue.min.js?20201130:6)
    at wn.$mount (vue.min.js?20201130:6)
    at wn.t._init (vue.min.js?20201130:6)
    at new wn (vue.min.js?20201130:6)
Ue @ vue.min.js?20201130:6
vue-blox.js?20201130:1924`

`Uncaught TypeError: Cannot read property 'parentNode' of null
    at vue-blox.js?20201130:1924
    at XMLHttpRequest.httpRequest.onreadystatechange (author.js?20201130:66) 6vue.min.js?20201130:6`

`ReferenceError: ct is not defined
    at wn.eval (eval at Ya (vue.min.js?20201130:6), <anonymous>:3:471)
    at wn.e._render (vue.min.js?20201130:6)
    at wn.r (vue.min.js?20201130:6)
    at fn.get (vue.min.js?20201130:6)
    at fn.run (vue.min.js?20201130:6)
    at un (vue.min.js?20201130:6)
    at Array.<anonymous> (vue.min.js?20201130:6)
    at qe (vue.min.js?20201130:6)
Ue @ vue.min.js?20201130:6`

`DevTools failed to load SourceMap: Could not load content for http://192.168.10.53/wiki/system/author/js/vuedraggable.umd.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

`DevTools failed to load SourceMap: Could not load content for http://192.168.10.53/wiki/system/author/js/axios.min.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

but the problem is, not all articles are effected, only this one.
is there a way to fix this error?

**Comment by trendschau** [comment] 2020-12-13 19:53
thank you for reporting and pretty strange bug, especially if it only happens on that page. The error message complaints about 

    var initialcontent = document.getElementById("initial-content");
    initialcontent.parentNode.removeChild(initialcontent);

The element "initial-content" is part of the twig-template, so I don't see any reason why it does not find it here. I have to reproduce it somehow to fix, so can you send me the content file for that page? Do you use any plugin or any additional code on that page?

Thank you

**Comment by rantwolf** [comment] 2020-12-29 20:27
Hi.
Sorry for the delay.

I'm using the following plugins: ebooks, highlight, search and thesarus.
The error is still there when all plugins are disabled.

Here's the content of the file:

> # discard-trim

> if the proxmox host is installed on solid state storage make sure to enable 'trim / discard' service.

> ````
> systemctl enable --now fstrim.timer
> ````

> this will enable the discard service and also starts the service immediately.
> when vm's are installed on a solid state storage enable also the `fstrim.timer service`.

> ````
> systemctl enable --now fstrim.timer
> ````

> to trim all containers use the following dirty one liner in the shell of the host.

> ````
> pct list | awk '/^[0-9]/ {print $1}' | while read ct; do pct fstrim ${ct}; done
> ````

**Comment by trendschau** [comment] 2021-01-07 22:04
sorry for the late answer, I just had the time to test it and I get the same error. 

The problem is that the syntax `${ ... }` is defined as the delimiter for the vue-app, because the default vue delimiters clash with the twig-syntax (see https://vuejs.org/v2/api/#delimiters). I don*t have a quick solution for it right now and can't offer a solution with version 1.4.3 because it will be published tomorrow. But I will think about a solution for the 1.4.4 release.

**Comment by rantwolf** [comment] 2021-05-04 20:51
Hi.
Are there any news about the bug in typemill?
It would be nice if you have a solution...

**Comment by trendschau** [comment] 2021-05-05 07:06
I did not had the time to find a fix for this, but will look into this issue for the next release. 

Just for me as a reminder: 

* https://github.com/vuejs/vue/issues/4223
* https://vuejs.org/v2/api/#v-pre

**Comment by trendschau** [comment] 2021-05-12 17:09
fixed it for release 1.4.6 (simple v-pre tag on the initially loaded content). I will publish the release end of May latest.

**Comment by trendschau** [comment] 2021-05-18 19:35
If that bug is critical for your work, then you can fix it directly in your code or use the develop branch that I just updated. I do not know when I find the time to finish the next release. The fix is pretty trivial, just a v-pre tag in one template, it prevents vue from rendering the initial content: https://github.com/typemill/typemill/blob/develop/system/author/editor/editor-blox.twig

`<div id="initial-content" v-pre>`

**Comment by trendschau** [comment] 2021-06-13 16:39
published today with 1.4.6

**Closed by trendschau** 2021-06-13 16:39 UTC
Labels: bug

**Comment by rantwolf** [comment] 2021-06-28 17:08
Thanks. Works fine and for now inside the package.
