### ISSUE TITLE
Please, help, dont add article

### ISSUE THREAD

**Issue by sopkomir** [typemill/typemill#342] opened 2022-06-20 11:11 UTC
Please help, after upgrading to version 1.5.3.3 I can't see or add new articles for News. Nothing like this has happened to me yet. I've tried more browsers, but the option to add an article doesn't work.

**Comment by trendschau** [comment] 2022-06-20 12:42
I can't reproduce that, it works fine on my websites. 

Do you use the rss-plugin? It has an error, I will try to update this evening, you should disable it for now.

**Comment by sopkomir** [comment] 2022-06-20 14:10
> I can't reproduce that, it works fine on my websites.
> 
> Do you use the rss-plugin? It has an error, I will try to update this evening, you should disable it for now.

Sorry, I stressed, helped update all plugins, it already works. Thanks.

**Comment by trendschau** [comment] 2022-07-14 12:32
Great to hear, I will close this ticket then

**Closed by trendschau** 2022-07-14 12:32 UTC
